    hs.graphicsDir = '/jscript/highslide/graphics/';
    hs.creditsPosition = 'bottom left';
    hs.outlineType = 'rounded-black';
    hs.dimmingOpacity = 0.6;
    hs.align = 'center';
    hs.creditsText = '';
    hs.easing = 'easeInCirc';
    hs.expandDuration = 600;
    hs.restoreDuration = 400;